### ISSUE TITLE
RuntimeException with "Detected a bad mac" string. 

### ISSUE THREAD

**Issue by eduardo-villasboas** [Auties00/Whatsapp4j#204]
I am getting the following error after some time the server is started. The errors occurs without any interactions and after that I can not connect with same id before scann QRCode again.

Feb 19, 2023 3:38:35 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
        at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:455)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:100)
        at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:180)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:174)
        at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:123)
        at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)

Obs: I am running the server by using flag  JAVA_TOOL_OPTIONS=--enable-preview 

Have you any observation that could help me to get this code working?

I am putting an zip with my build.gradle.kts, main.kt and gradle 

[main-files.zip](https://github.com/Auties00/WhatsappWeb4j/files/10777671/main-files.zip)

Is there something wrong with my configs?

Thank you.

**Comment by Auties00** [comment]
> I am getting the following error after some time the server is started. The errors occurs without any interactions and after that I can not connect with same id before scann QRCode again.
> 
> Feb 19, 2023 3:38:35 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> SEVERE: Socket failure at CRYPTOGRAPHY
> java.lang.RuntimeException: Detected a bad mac
>         at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:455)
>         at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:100)
>         at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:180)
>         at java.base/java.lang.Iterable.forEach(Iterable.java:75)
>         at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:174)
>         at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:123)
>         at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
>         at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
>         at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
>         at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
>         at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
>         at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
>         at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
>         at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
>         at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
>         at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
>         at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
>         at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
>         at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
>         at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
>         at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
>         at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
>         at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
>         at java.base/java.lang.Thread.run(Thread.java:833)
> 
> 
> Obs: I am running the server by using flag  JAVA_TOOL_OPTIONS=--enable-preview 
> 
> Have you any observation that could help me to get this code working?
> 
> I am putting an zip with my build.gradle.kts, main.kt and gradle 
> 
> [main-files.zip](https://github.com/Auties00/WhatsappWeb4j/files/10777671/main-files.zip)
> 
> Is there something wrong with my configs?
> 
> Thank you.
> 
> 

Can you try to use my latest commit instead of 3.0.5? I've fixed that bug there afair

**Comment by eduardo-villasboas** [comment]
> > I am getting the following error after some time the server is started. The errors occurs without any interactions and after that I can not connect with same id before scann QRCode again.
> > Feb 19, 2023 3:38:35 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
> > SEVERE: Socket failure at CRYPTOGRAPHY
> > java.lang.RuntimeException: Detected a bad mac
> > at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:455)
> > at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:100)
> > at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:180)
> > at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> > at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:174)
> > at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:123)
> > at jdk.internal.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
> > at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> > at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
> > at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
> > at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
> > at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
> > at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
> > at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
> > at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
> > at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
> > at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
> > at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
> > at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
> > at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
> > at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
> > at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
> > at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
> > at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
> > at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
> > at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
> > at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
> > at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
> > at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
> > at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
> > at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
> > at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
> > at java.base/java.lang.Thread.run(Thread.java:833)
> > Obs: I am running the server by using flag  JAVA_TOOL_OPTIONS=--enable-preview
> > Have you any observation that could help me to get this code working?
> > I am putting an zip with my build.gradle.kts, main.kt and gradle
> > [main-files.zip](https://github.com/Auties00/WhatsappWeb4j/files/10777671/main-files.zip)
> > Is there something wrong with my configs?
> > Thank you.
> 
> Can you try to use my latest commit instead of 3.0.5? I've fixed that bug there afair

Thanks. I built the library locally using maven 3.9.0 and java17. I am not getting this error anymore.
