### ISSUE TITLE
After crash of the JVM and restart app I catched java.io.UncheckedIOException: Corrupted keys on initializing connection

### ISSUE THREAD

**Issue by stserakhau** [Auties00/Whatsapp4j#215]
Hi,

After crash of the JVM and restart app I catched java.io.UncheckedIOException: Corrupted keys on initializing connection

```
<dependency>
    <groupId>com.github.auties00</groupId>
    <artifactId>whatsappweb4j</artifactId>
    <version>3.1.2</version>
</dependency>


Exception in thread "pool-2-thread-1" java.io.UncheckedIOException: Corrupted keys
	at it.auties.whatsapp.serialization.DefaultControllerProvider.deserializeKeys(DefaultControllerProvider.java:106)
	at it.auties.whatsapp.controller.Keys.of(Keys.java:208)
	at it.auties.whatsapp.api.Whatsapp.<init>(Whatsapp.java:87)
	at it.auties.whatsapp.api.Whatsapp.newConnection(Whatsapp.java:143)
	at it.auties.whatsapp.api.Whatsapp.lastConnection(Whatsapp.java:205)
	at com.banalytics.box.module.whatsapp.WhatsAppBotThing.lambda$doStart$1(WhatsAppBotThing.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Invalid type marker byte 0x35 for expected field name (or END_OBJECT marker)
 at [Source: (GZIPInputStream); byte offset: #11549] (through reference chain: it.auties.whatsapp.controller.Keys$KeysBuilder["hashStates"]->java.util.ArrayList[1]->it.auties.map.MapEntry["value"]->it.auties.whatsapp.model.sync.LTHashState$LTHashStateBuilder["indexValueMap"]->java.util.ArrayList[58])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:371)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:966)
	at it.auties.map.MapDeserializer.deserialize(MapDeserializer.java:30)
	at it.auties.map.MapDeserializer.deserialize(MapDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.DeserializationContext.readValue(DeserializationContext.java:966)
	at it.auties.map.MapDeserializer.deserialize(MapDeserializer.java:30)
	at it.auties.map.MapDeserializer.deserialize(MapDeserializer.java:16)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at it.auties.whatsapp.serialization.SmileFile.read(SmileFile.java:53)
	at it.auties.whatsapp.serialization.SmileFile.read(SmileFile.java:40)
	at it.auties.whatsapp.serialization.DefaultControllerProvider.deserializeKeys(DefaultControllerProvider.java:104)
	... 8 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid type marker byte 0x35 for expected field name (or END_OBJECT marker)
 at [Source: (GZIPInputStream); byte offset: #11549]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2444)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2448)
	at com.fasterxml.jackson.dataformat.smile.SmileParser._handleFieldName(SmileParser.java:1454)
	at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:412)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:423)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	... 37 more
```

**Comment by stserakhau** [comment]
one more case with jvm crash (simulated via hard stop app in intellij viar red square)

```
2023-03-06 22:12:23.294 [ForkJoinPool.commonPool-worker-7] ERROR Deserializer - Chat 1234123412@s.whatsapp.net is corrupted, resetting it
com.fasterxml.jackson.databind.JsonMappingException: Invalid type marker byte 0x38 for expected field name (or END_OBJECT marker)
 at [Source: (GZIPInputStream); byte offset: #54921] (through reference chain: it.auties.whatsapp.model.chat.Chat$ChatBuilder["messages"]->java.util.concurrent.ConcurrentLinkedDeque[290]->it.auties.whatsapp.model.info.MessageInfo$MessageInfoBuilder["key"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1821)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3674)
	at it.auties.whatsapp.serialization.SmileFile.read(SmileFile.java:53)
	at it.auties.whatsapp.serialization.SmileFile.read(SmileFile.java:40)
	at it.auties.whatsapp.serialization.DefaultControllerProvider.lambda$deserializeChat$7(DefaultControllerProvider.java:147)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid type marker byte 0x38 for expected field name (or END_OBJECT marker)
 at [Source: (GZIPInputStream); byte offset: #54921]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2418)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2444)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2448)
	at com.fasterxml.jackson.dataformat.smile.SmileParser._handleFieldName(SmileParser.java:1454)
	at com.fasterxml.jackson.dataformat.smile.SmileParser.nextToken(SmileParser.java:412)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
	at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
	... 22 common frames omitted
```

**Comment by Auties00** [comment]
I understand the issue and I'm aware of it, yet I'm not sure how to fix it. The serialization process will start when the JVM shuts down, but if it crashes if will not finish which corrupts the session's data. Perhaps writing the data atomically(i.e. with a transaction) would solve the issue. I'll see what I can do

**Comment by stserakhau** [comment]
I think about this flow

1. Start transaction - create new file / folder
2. Save new data to temporary file/folder
3. output stream closed
4. Commit
     4.1. Copy original file/folder to rollback folder
     4.2. Copy transactional data to target folder
     4.3. Drop file 2.1.
     4.4. Drop temp file 1

Exists very much different failure cases in point 4, but it will decrease probability of corrupted data.
Plus if code contains peaces which hold opened streams need to make sure that these buffers after each write operation are flushed to disk.

**Comment by Auties00** [comment]
> I think about this flow
> 
> 1. Start transaction - create new file / folder
> 2. Save new data to temporary file/folder
> 3. output stream closed
> 4. Commit
>    4.1. Copy original file/folder to rollback folder
>    4.2. Copy transactional data to target folder
>    4.3. Drop file 2.1.
>    4.4. Drop temp file 1
> 
> Exists very much different failure cases in point 4, but it will decrease probability of corrupted data. Plus if code contains peaces which hold opened streams need to make sure that these buffers after each write operation are flushed to disk.
> 
> https://stackoverflow.com/questions/1311050/transaction-mode-for-file-operations-in-java
> 
> https://commons.apache.org/proper/commons-transaction/file/index.html

I've implemented something similar, can you please try the latest commit I pushed?
In practice, before I was using a GZipOutputStream directly linked to the file, so if anything went wrong during serialization everything would get corrupted. Now I switched that to an intermediary byte array that I then write to the file. I have simulated a couple of JVM crashes and it looks like it's fixed.

**Comment by stserakhau** [comment]
thx, will try

**Comment by stserakhau** [comment]
not reproduced, thx
