### ISSUE TITLE
Socket failure expection on onChatMessagesSync on startup

### ISSUE THREAD

**Issue by softnrajkumar1994** [Auties00/Whatsapp4j#225]
[ient-SecureIO-2] ErrorHandler                             : Socket failure at UNKNOWN
it.auties.protobuf.serialization.exception.ProtobufDeserializationException: Protocol message had invalid wire type
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:185)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readMessage(Protobuf.java:57)
	at it.auties.whatsapp.socket.AuthHandler.loginSocket(AuthHandler.java:59)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:189)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:135)
	at jdk.internal.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:105)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:602)
	at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:561)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:307)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:474)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:338)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

**Comment by softnrajkumar1994** [comment]
```
java.lang.RuntimeException: Cannot decrypt data using AesGMC: 0c68a9d4a4c7a98102d08e7c86eecebbc1802325769239e602e4a17891c90433ec74125f2e6897fe53a9639b214d8e38
	at it.auties.whatsapp.crypto.AesGmc.cipher(AesGmc.java:35)
	at it.auties.whatsapp.crypto.AesGmc.decrypt(AesGmc.java:48)
	at it.auties.whatsapp.crypto.Handshake.cipher(Handshake.java:32)
	at it.auties.whatsapp.socket.AuthHandler.loginSocket(AuthHandler.java:65)
2023-03-14T19:47:39.969+05:30 ERROR 530554 --- [ient-SecureIO-2] ErrorHandler                             : Ignored failure
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:189)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:135)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:105)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:602)
	at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:561)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:307)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:474)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:338)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in GCM failed
	at org.bouncycastle.crypto.modes.GCMBlockCipher.doFinal(Unknown Source)
	at it.auties.whatsapp.crypto.AesGmc.cipher(AesGmc.java:32)
	... 23 more
2023-03-14T19:47:39.971+05:30 ERROR 530554 --- [ient-SecureIO-2] ErrorHandler                             : Ignored failure


```

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Whatsapp4j/issues/212
