### ISSUE TITLE
After a successful login , its again asking me to login

### ISSUE THREAD

**Issue by softnrajkumar1994** [Auties00/Whatsapp4j#226]
2023-03-14T19:53:52.348+05:30 ERROR 537440 --- [ient-SecureIO-2] ErrorHandler                             : Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:456)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:84)
	at it.auties.whatsapp.socket.SocketHandler.handleNode(SocketHandler.java:198)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:192)
	at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:135)
	at jdk.internal.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.tomcat.websocket.pojo.PojoMessageHandlerWholeBase.onMessage(PojoMessageHandlerWholeBase.java:105)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageBinary(WsFrameBase.java:602)
	at org.apache.tomcat.websocket.WsFrameBase.processDataBinary(WsFrameBase.java:561)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:307)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
	at org.apache.tomcat.websocket.WsFrameClient.processSocketRead(WsFrameClient.java:95)
	at org.apache.tomcat.websocket.WsFrameClient.resumeProcessing(WsFrameClient.java:212)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.doResumeProcessing(WsFrameClient.java:189)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:163)
	at org.apache.tomcat.websocket.WsFrameClient$WsFrameClientCompletionHandler.completed(WsFrameClient.java:148)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$WrapperFuture.complete(AsyncChannelWrapperSecure.java:474)
	at org.apache.tomcat.websocket.AsyncChannelWrapperSecure$ReadTask.run(AsyncChannelWrapperSecure.java:338)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-03-14T19:53:52.350+05:30 ERROR 537440 --- [ient-SecureIO-2] ErrorHandler                             : Restoring session
█████████████████████████████████████████████████████████
██ ▄▄▄▄▄ █▀ ▄██▄▀▄██▀ ▀██ ▄ ▄██▄▄█ ▀▀▄█▄▀ ██ ▀██ ▄▄▄▄▄ ██
██ █   █ █▀▄▀▀▀ ▄ █ ▀  ▄█▀██▀▄ ▄ ▄▄█ ▀ ▄▀▄▄▀▀▄▀█ █   █ ██
██ █▄▄▄█ █▀▄▄█▀  █▀█  ▀▀▀▄ ▄▄▄ ▄▄▀██▀▀▀▄▀▄▄▄ ███ █▄▄▄█ ██
██▄▄▄▄▄▄▄█▄█ ▀▄█ █ ▀▄▀ █▄█ █▄█ █▄█▄▀▄█ ▀ █ ▀ ▀▄█▄▄▄▄▄▄▄██
██

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Whatsapp4j/issues/212
