### ISSUE TITLE
Duplicate key CELL

### ISSUE THREAD

**Issue by 19Maury85** [Auties00/Whatsapp4j#233]
Probably I have a duplicate contact with same phone number:

mar 22, 2023 12:03:49 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
SEVERE: Socket failure at MESSAGE
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Duplicate key CELL (attempted merging values 39xxxxxxxxxxx@s.whatsapp.net and 39xxxxxxxxxxx@s.whatsapp.net)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.IllegalStateException: Duplicate key CELL (attempted merging values 39xxxxxxxxxxx@s.whatsapp.net and 39xxxxxxxxxxx@s.whatsapp.net)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at it.auties.whatsapp.model.contact.ContactCard.of(ContactCard.java:80)
	at it.auties.whatsapp.model.contact.ContactCard.convert(ContactCard.java:62)
	at it.auties.protobuf.ProtobufStubs$1$118.lambda$new$2(ProtobufStubs.java:3)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:92)
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:159)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:159)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:159)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:159)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readFieldContent(Protobuf.java:159)
	at it.auties.protobuf.serialization.performance.Protobuf.decode(Protobuf.java:89)
	at it.auties.protobuf.serialization.performance.Protobuf.readMessage(Protobuf.java:57)
	at it.auties.whatsapp.socket.MessageHandler.lambda$downloadHistorySync$60(MessageHandler.java:669)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 6 more
mar 22, 2023 12:03:49 AM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
SEVERE: Ignored failure

**Comment by Auties00** [comment]
Thanks for reporting this issue.
Will be fixed on the next release

**Comment by Auties00** [comment]
Fixed in 3.2.2
