### ISSUE TITLE
What is the cause of this exception

### ISSUE THREAD

**Issue by liufei940309** [Auties00/Whatsapp4j#246]
java.util.NoSuchElementException: Cannot find state with id 673772658
	at it.auties.whatsapp.model.signal.sender.SenderKeyRecord.lambda$findStateById$1(SenderKeyRecord.java:43) ~[classes!/:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at it.auties.whatsapp.model.signal.sender.SenderKeyRecord.findStateById(SenderKeyRecord.java:43) ~[classes!/:na]
	at it.auties.whatsapp.crypto.GroupCipher.decrypt(GroupCipher.java:38) ~[classes!/:na]
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:469) ~[classes!/:na]
	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:430) ~[classes!/:na]
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$35(MessageHandler.java:374) ~[classes!/:na]

**Comment by Auties00** [comment]
> java.util.NoSuchElementException: Cannot find state with id 673772658
> 	at it.auties.whatsapp.model.signal.sender.SenderKeyRecord.lambda$findStateById$1(SenderKeyRecord.java:43) ~[classes!/:na]
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
> 	at it.auties.whatsapp.model.signal.sender.SenderKeyRecord.findStateById(SenderKeyRecord.java:43) ~[classes!/:na]
> 	at it.auties.whatsapp.crypto.GroupCipher.decrypt(GroupCipher.java:38) ~[classes!/:na]
> 	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:469) ~[classes!/:na]
> 	at it.auties.whatsapp.socket.MessageHandler.decode(MessageHandler.java:430) ~[classes!/:na]
> 	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$35(MessageHandler.java:374) ~[classes!/:na]

Probably a corrupted session
