### ISSUE TITLE
Chats#messages is not a Concurrent collection

### ISSUE THREAD

**Issue by ZiemlichUndead** [Auties00/Whatsapp4j#251]
v3.2.3(web) was up and running for a while (approx. 2 Days).
Then I wanted to see how stable it would be when spammed with messages so i sent around 20 messages at once (done by hand with a keyboard).

Whatsapp4j then dropped the session with this exception:
Apr 05, 2023 4:51:33 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
        at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:520)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:83)
        at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:169)
        at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:157)
        at jdk.internal.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
Apr 05, 2023 4:51:34 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Socket failure at CRYPTOGRAPHY

I tried replicating it by creating a new session and spamming again but it seemed to handle it fine with no errors.

I will keep it running again and try to replicate it in a bit.

**Comment by ZiemlichUndead** [comment]
So tried same thing today. Before the session drop i noticed that responses were really slow already. When i then sent more messages at a time same thing happened as last time.
I did also get this exception prior to the drop. Not sure if it has something to do with it tho:
java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot complete file write
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.UncheckedIOException: Cannot complete file write
        at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.writeSync(DefaultControllerSerializer.java:349)
        at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.lambda$write$0(DefaultControllerSerializer.java:327)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 1 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: it.auties.whatsapp.model.chat.Chat["messages"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3892)
        at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.writeSync(DefaultControllerSerializer.java:337)
        ... 3 more
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:165)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        ... 9 more

**Comment by Auties00** [comment]
I've noticed this myself.
I need to find a ConcurrentLinkedList or write one.
I already tried yesterday but it was so bad in terms of memory efficiency I had to kill it.
This issue is kind of important, I'll have it fixed asap

**Comment by Auties00** [comment]
Should be fixed in 3.3.0
Can you test it out? @ZiemlichUndead

**Comment by ZiemlichUndead** [comment]
Yes I am at it

**Comment by ZiemlichUndead** [comment]
> So tried same thing today after one day of uptime. Before the session drop i noticed that responses were really slow already. When i then sent more messages at a time same thing happened as last time. I did also get this exception prior to the drop. Not sure if it has something to do with it tho:
> 
> java.util.concurrent.CompletionException: java.io.UncheckedIOException: Cannot complete file write at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807) at java.base/java.lang.Thread.run(Thread.java:833) Caused by: java.io.UncheckedIOException: Cannot complete file write at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.writeSync(DefaultControllerSerializer.java:349) at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.lambda$write$0(DefaultControllerSerializer.java:327) at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ... 1 more Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: it.auties.whatsapp.model.chat.Chat["messages"]) at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402) at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361) at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316) at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:782) at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178) at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480) at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319) at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4624) at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3892) at it.auties.whatsapp.controller.DefaultControllerSerializer$SmileFile.writeSync(DefaultControllerSerializer.java:337) ... 3 more Caused by: java.util.ConcurrentModificationException at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970) at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892) at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContentsUsing(CollectionSerializer.java:165) at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:116) at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107) at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25) at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:733) at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774) ... 9 more

Being on 3.3.0 I did not get this error again until now.

However I did get the same exception as in my first post:
java.lang.RuntimeException: Detected a bad mac
        at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:528)
        at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:84)
        at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:162)
        at it.auties.whatsapp.socket.SocketSession$WebSocketSession.onBinary(SocketSession.java:165)
        at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:556)
        at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:655)
        at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:591)
        at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:806)
        at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:183)
        at org.glassfish.tyrus.core.frame.BinaryFrame.respond(BinaryFrame.java:70)
        at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
        at org.glassfish.tyrus.client.TyrusClientEngine$TyrusReadHandler.handle(TyrusClientEngine.java:726)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter$ProcessTask.execute(GrizzlyClientFilter.java:452)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:91)
        at org.glassfish.tyrus.container.grizzly.client.TaskProcessor.processTask(TaskProcessor.java:68)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientFilter.handleRead(GrizzlyClientFilter.java:248)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
        at java.base/java.lang.Thread.run(Thread.java:833)
Disconnected: 
RESTORE

Same behaviour  as last time. Problem seems to occur when many messages are received at a time. Session drops.

**Comment by daniloleiter** [comment]
I am getting the same error (ConcurrentModificationException) on 3.3.1.
I have a rabbit queue with around 70 messages. Each message is processed at a time synchronously (the ack is only sent when the sendMessage method completes). The library successfully sends around 10 or 20 messages (varies everytime) and then I get the error.
Please let me know if you need any additional info.
@Auties00 @ZiemlichUndead

**Comment by Auties00** [comment]
> I am getting the same error (ConcurrentModificationException) on 3.3.1.
> I have a rabbit queue with around 70 messages. Each message is processed at a time synchronously (the ack is only sent when the sendMessage method completes). The library successfully sends around 10 or 20 messages (varies everytime) and then I get the error.
> Please let me know if you need any additional info.
> @Auties00 @ZiemlichUndead 

Can you send the exact stack trace?

**Comment by daniloleiter** [comment]
I purged the keys, scanned QR Code again and have not had this error again since. I am encountering many other errors that happen randomly (bad mac detected, hasWhatsapp found no jid) and they all lose my connection forcing me to scan the QR code again. How do you handle these?

**Comment by Auties00** [comment]
> I purged the keys, scanned QR Code again and have not had this error again since. I am encountering many other errors that happen randomly (bad mac detected, hasWhatsapp found no jid) and they all lose my connection forcing me to scan the QR code again. How do you handle these? 

I mean report them?

**Comment by daniloleiter** [comment]
In the last commit the issue appears to have been solved. The bad mac detected issue also appears to have been completely solved in the last commit.
