### ISSUE TITLE
Error when receiving pool updates

### ISSUE THREAD

**Issue by PandaTwoo** [Auties00/Whatsapp4j#256]
When someone creates/votes on a whatsapp pool, the console throws the following error;

`abr. 12, 2023 1:41:01 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
GRAVE: Socket failure at POLL
java.lang.ClassCastException: class it.auties.whatsapp.model.message.standard.EmptyMessage cannot be cast to class it.auties.whatsapp.model.message.standard.PollCreationMessage (it.auties.whatsapp.model.message.standard.EmptyMessage and it.auties.whatsapp.model.message.standard.PollCreationMessage are in unnamed module of loader 'app')
	at it.auties.whatsapp.socket.MessageHandler.handlePollUpdate(MessageHandler.java:622)
	at it.auties.whatsapp.socket.MessageHandler.processMessage(MessageHandler.java:551)
	at it.auties.whatsapp.socket.MessageHandler.saveMessage(MessageHandler.java:510)
	at it.auties.whatsapp.socket.MessageHandler.decodeMessage(MessageHandler.java:434)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decodeMessages$44(MessageHandler.java:366)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at it.auties.whatsapp.socket.MessageHandler.decodeMessages(MessageHandler.java:366)
	at it.auties.whatsapp.socket.MessageHandler.lambda$decode$43(MessageHandler.java:355)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
abr. 12, 2023 1:41:01 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0
GRAVE: Ignored failure`

**Comment by Auties00** [comment]
> When someone creates/votes on a whatsapp pool, the console throws the following error;
> 
> `abr. 12, 2023 1:41:01 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0 GRAVE: Socket failure at POLL java.lang.ClassCastException: class it.auties.whatsapp.model.message.standard.EmptyMessage cannot be cast to class it.auties.whatsapp.model.message.standard.PollCreationMessage (it.auties.whatsapp.model.message.standard.EmptyMessage and it.auties.whatsapp.model.message.standard.PollCreationMessage are in unnamed module of loader 'app') at it.auties.whatsapp.socket.MessageHandler.handlePollUpdate(MessageHandler.java:622) at it.auties.whatsapp.socket.MessageHandler.processMessage(MessageHandler.java:551) at it.auties.whatsapp.socket.MessageHandler.saveMessage(MessageHandler.java:510) at it.auties.whatsapp.socket.MessageHandler.decodeMessage(MessageHandler.java:434) at it.auties.whatsapp.socket.MessageHandler.lambda$decodeMessages$44(MessageHandler.java:366) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at it.auties.whatsapp.socket.MessageHandler.decodeMessages(MessageHandler.java:366) at it.auties.whatsapp.socket.MessageHandler.lambda$decode$43(MessageHandler.java:355) at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) abr. 12, 2023 1:41:01 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$0 GRAVE: Ignored failure`

This is fixed on the master branch

**Comment by Auties00** [comment]
Fixed in 3.3.0
