### ISSUE TITLE
register missing_param

### ISSUE THREAD

**Issue by hurunboy** [Auties00/Whatsapp4j#279]
{reason=, authkey=58pHomSS7KQlIF303anpPexIPPwXsIXQGgaATXuZqCc=, e_skey_sig=DDIWjj3wcih2F60ejgkTPx2gt3gBvZ7TQkp2gnZqjlLPt3Og-4dgqcbK9lFGMMYZQaC5UGWKHcBANTog9oj7iQ==, pid=18824, mcc=222, e_skey_id=ADlO, mistyped=6, id=e4a8a44613671f27865a7c51474b26b7a6a6a2ea, cc=39, network_radio_type=1, mnc=001, sim_mcc=000, method=sms, hasinrc=1, in=3495089819, hasav=1, token=iB_hT1oDnUuiy7vPq2oZsQVdvXQ=, rc=0, e_regid=AAA5Tg==, fdid=15e611bd-2495-4809-ab83-947965e6a403, lc=GB, simnum=1, e_skey_val=PVKuUSOuUVHqsyd8ZnV_31OgV3ZOmql8IJ5ZSecU32E=, lg=en, sim_mnc=000, e_ident=FxvHuUSiL2A7XO2ehsvGBgl8Vqm4xWG4OUXox4gpjl4=, expid=wc8yun-IvadC7dx2UqmcYg==}
java.util.concurrent.CompletionException: it.auties.whatsapp.exception.RegistrationException: Invalid response: {"login":"393495089819","param":"e_keytype","reason":"missing_param","status":"fail"}

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:722)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: it.auties.whatsapp.exception.RegistrationException: Invalid response: {"login":"393495089819","param":"e_keytype","reason":"missing_param","status":"fail"}

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at it.auties.whatsapp.util.RegistrationHelper.checkResponse(RegistrationHelper.java:93)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:718)

**Comment by Auties00** [comment]
try the latest commit
