### ISSUE TITLE
Cannot create link between store and phone number

### ISSUE THREAD

**Issue by Goddino-Repo** [Auties00/Whatsapp4j#290]
With the new version on maven central, I scan the QR code and I get this stack trace:
```
mag 21, 2023 9:46:09 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at UNKNOWN
java.io.UncheckedIOException: Cannot create link between store and phone number
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:255)
	at it.auties.whatsapp.controller.Store.phoneNumber(Store.java:1175)
	at it.auties.whatsapp.socket.StreamHandler.saveCompanion(StreamHandler.java:832)
	at it.auties.whatsapp.socket.StreamHandler.confirmQrCode(StreamHandler.java:782)
	at it.auties.whatsapp.socket.StreamHandler.digestIq(StreamHandler.java:740)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:86)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:172)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.FileSystemException: C:\Users\Utente\.whatsapp4j\web\349*******: Il privilegio richiesto non appartiene al client
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:598)
	at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:253)
	... 14 more
mag 21, 2023 9:46:09 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
Connected
mag 21, 2023 9:46:10 PM com.config.Core onLoggedIn
INFO: Logged in!
mag 21, 2023 9:46:11 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
SEVERE: Socket failure at MESSAGE
java.util.concurrent.CompletionException: it.auties.protobuf.base.ProtobufSerializationException: Cannot invoke "Object.getClass()" because "object" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: it.auties.protobuf.base.ProtobufSerializationException: Cannot invoke "Object.getClass()" because "object" is null
	at it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:22)
	at it.auties.whatsapp.socket.MessageHandler.createEncodedMessageNode(MessageHandler.java:200)
	at it.auties.whatsapp.socket.MessageHandler.lambda$encodeConversation$13(MessageHandler.java:165)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 7 more
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "object" is null
	at it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:19)
	... 10 more
mag 21, 2023 9:46:11 PM it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
WARNING: Ignored failure
Disconnected: LOGGED_OUT
Disconnected from the target VM, address: '127.0.0.1:62579', transport: 'socket'

Process finished with exit code 0
```

**Comment by GDB4J** [comment]
@Auties00 
Same issue for me (last version 3.4.0)

Not able to login
Nothing is persists on folder ".whatsapp4j"

**Comment by Auties00** [comment]
I'll have it fixed, thanks for the report

**Comment by GDB4J** [comment]
> fixed in 3.4.1

@Auties00 
Thanks for the quick fix.
Any ETA when version 3.4.1 wil be available on Maven Repository?

**Comment by GDB4J** [comment]
@Auties00 
- Problem still exists in version 3.4.1
- immediately after scanning the QR code
- Nothing is stored at C:\Users\xxx\.whatsapp4j\web\

```
java.io.UncheckedIOException: Cannot create link between store and phone number
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:264)
	at it.auties.whatsapp.controller.Controller.phoneNumber(Controller.java:98)
	at it.auties.whatsapp.socket.StreamHandler.saveCompanion(StreamHandler.java:851)
	at it.auties.whatsapp.socket.StreamHandler.confirmQrCode(StreamHandler.java:801)
	at it.auties.whatsapp.socket.StreamHandler.digestIq(StreamHandler.java:759)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:87)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:188)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.nio.file.FileSystemException: C:\Users\xxx\.whatsapp4j\web\xxxxx: Een van de vereiste bevoegdheden is niet aan de client toegekend
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:598)
	at java.base/java.nio.file.Files.createSymbolicLink(Files.java:1069)
	at it.auties.whatsapp.controller.DefaultControllerSerializer.linkPhoneNumber(DefaultControllerSerializer.java:262)
	... 14 common frames omitted
```

**Comment by tomlux** [comment]
should be related to this:
 https://stackoverflow.com/questions/23217460/how-to-create-soft-symbolic-link-using-java-nio-files

**Comment by GDB4J** [comment]
> should be related to this: https://stackoverflow.com/questions/23217460/how-to-create-soft-symbolic-link-using-java-nio-files

Thanks
That fixed the problem indeed (aslo was only on windows)

But now i got this stacktrace:
```
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: null
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.addAll(ConcurrentHashMap.java:4747)
	at it.auties.whatsapp.socket.SocketHandler.handleGroupMetadata(SocketHandler.java:484)
	at it.auties.whatsapp.socket.SocketHandler.lambda$queryGroupMetadata$19(SocketHandler.java:472)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 7 common frames omitted
``` 

Same issue as in https://github.com/Auties00/Whatsapp4j/issues/296
