### ISSUE TITLE
NoSuchMethodException: it.auties.whatsapp.model.signal.auth.HandshakeMessage.toEncodedProtobuf()

### ISSUE THREAD

**Issue by ripreal** [Auties00/Whatsapp4j#293]
Whenever i run project  from sources i always get the error 

```
Exception in thread "main" java.util.concurrent.CompletionException: it.auties.protobuf.base.ProtobufSerializationException: it.auties.whatsapp.model.signal.auth.HandshakeMessage.toEncodedProtobuf()
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: it.auties.protobuf.base.ProtobufSerializationException: it.auties.whatsapp.model.signal.auth.HandshakeMessage.toEncodedProtobuf()
	at it.auties.whatsapp4j/it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:22)
	at it.auties.whatsapp4j/it.auties.whatsapp.model.request.Request.of(Request.java:71)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketHandler.onOpen(SocketHandler.java:151)
	at it.auties.whatsapp4j/it.auties.whatsapp.socket.SocketSession.lambda$connect$0(SocketSession.java:47)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1804)
	... 8 more
Caused by: java.lang.NoSuchMethodException: it.auties.whatsapp.model.signal.auth.HandshakeMessage.toEncodedProtobuf()
	at java.base/java.lang.Class.getMethod(Class.java:2227)
	at it.auties.whatsapp4j/it.auties.whatsapp.util.Protobuf.writeMessage(Protobuf.java:19)
	... 12 more
Disconnected from the target VM, address: '127.0.0.1:63442', transport: 'socket'

Process finished with exit code 1
```
I use simple registration code 
```     
Whatsapp.webBuilder()
  .newConnection()
  .build()
  .addLoggedInListener(() -> System.out.println("Connected"))
  .addDisconnectedListener(reason -> System.out.printf("Disconnected: %s%n", reason))
  .connect()
  .join();`
```

If i run it as a dependency then everything is ok. Could you elaborate me on this?

**Comment by Auties00** [comment]
![image](https://github.com/Auties00/Whatsapp4j/assets/28218457/6285257d-5a0f-4241-bad4-94072533b379)
In IntelliJ, enable this option
