### ISSUE TITLE
When the scan login is successful, an error will be prompted.

### ISSUE THREAD

**Issue by koalsky** [Auties00/Whatsapp4j#305]
Before I scanned the QR code, there were no issues.

When the scan login is successful, an error will be prompted.

code:
`
Whatsapp whatsapp = null;
        try {
            whatsapp = Whatsapp.webBuilder()
                    .newConnection()
                    .qrHandler(QrHandler.toFile(QrHandler.ToFileConsumer.toDesktop()))
                    .name("MX-AI")
                    .build()
                    .addLoggedInListener(() -> System.out.println("Connected"))
                    .addMessageReplyListener((messageInfo, quotedMessage) -> {
                        System.err.println(messageInfo.chatJid());
                        System.err.println(quotedMessage.message());
                    })
                    .addDisconnectedListener(reason -> System.out.printf("Disconnected: %s%n", reason));

            whatsapp.connect().join();
        } catch (Exception e) {
            if (whatsapp != null) {
                whatsapp.logout();
            }
        }

`

![image](https://github.com/Auties00/Whatsapp4j/assets/11881492/f0b8505c-442a-46b2-9c38-e1555fe8ce04)

error:
`
Disconnected: RECONNECTING
5月 28, 2023 6:44:01 下午 it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
严重: Socket failure at CRYPTOGRAPHY
java.lang.RuntimeException: Detected a bad mac
	at it.auties.whatsapp.socket.StreamHandler.digestError(StreamHandler.java:547)
	at it.auties.whatsapp.socket.StreamHandler.digest(StreamHandler.java:88)
	at it.auties.whatsapp.socket.SocketHandler.onMessage(SocketHandler.java:172)
	at it.auties.whatsapp.socket.SocketSession.readMessages(SocketSession.java:122)
	at java.base/java.lang.Thread.run(Thread.java:833)
5月 28, 2023 6:44:01 下午 it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
警告: Socket failure at CRYPTOGRAPHY
Disconnected: RESTORE
5月 28, 2023 6:44:01 下午 it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
严重: Socket failure at LOGIN
java.util.concurrent.CompletionException: java.util.NoSuchElementException: Missing block list in response
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.NoSuchElementException: Missing block list in response
	at it.auties.whatsapp.socket.SocketHandler.lambda$parseBlockList$17(SocketHandler.java:445)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at it.auties.whatsapp.socket.SocketHandler.parseBlockList(SocketHandler.java:445)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 2 more
5月 28, 2023 6:44:01 下午 it.auties.whatsapp.api.ErrorHandler lambda$defaultErrorHandler$1
警告: Ignored failure

`

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Whatsapp4j/issues/292
