### ISSUE TITLE
PBKDF2WithHmacSHA1And8BIT SecretKeyFactory not available

### ISSUE THREAD

**Issue by rocymp** [Auties00/Whatsapp4j#312]
`
Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA1And8BIT SecretKeyFactory not available
        at java.base/javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:118)
        at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:164)
        at it.auties.whatsapp.util.MetadataHelper.getSecretKey(MetadataHelper.java:215)
        at it.auties.whatsapp.util.MetadataHelper.getWhatsappData(MetadataHelper.java:167)

`

Version: 3.4.3

**Comment by Auties00** [comment]
> `
> Caused by: java.security.NoSuchAlgorithmException: PBKDF2WithHmacSHA1And8BIT SecretKeyFactory not available
>         at java.base/javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:118)
>         at java.base/javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:164)
>         at it.auties.whatsapp.util.MetadataHelper.getSecretKey(MetadataHelper.java:215)
>         at it.auties.whatsapp.util.MetadataHelper.getWhatsappData(MetadataHelper.java:167)
> 
> `
> 
> Version: 3.4.3

in what env are you running? what os?

**Comment by rocymp** [comment]
> 

mac os m2

**Comment by rocymp** [comment]
problem solved
