### ISSUE TITLE
UUIDs for store and keys don't match

### ISSUE THREAD

**Issue by rocymp** [Auties00/Whatsapp4j#315]
```
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: UUIDs for store and keys don't match
        at com.whatsapp.api.controller.OnlineController$1.apply(OnlineController.java:137)
        at com.whatsapp.api.controller.OnlineController$1.apply(OnlineController.java:134)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: UUIDs for store and keys don't match
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at it.auties.whatsapp.api.Whatsapp.of(Whatsapp.java:140)
        at com.whatsapp.api.controller.OnlineController.lambda$robots$0(OnlineController.java:105)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        ... 3 common frames omitted
```

Verson: 3.4.3

**Comment by Auties00** [comment]
> ```
> java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: UUIDs for store and keys don't match
>         at com.whatsapp.api.controller.OnlineController$1.apply(OnlineController.java:137)
>         at com.whatsapp.api.controller.OnlineController$1.apply(OnlineController.java:134)
>         at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
>         at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
>         at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
>         at java.base/java.lang.Thread.run(Thread.java:1589)
> Caused by: java.lang.IllegalArgumentException: UUIDs for store and keys don't match
>         at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
>         at it.auties.whatsapp.api.Whatsapp.of(Whatsapp.java:140)
>         at com.whatsapp.api.controller.OnlineController.lambda$robots$0(OnlineController.java:105)
>         at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
>         ... 3 common frames omitted
> ```
> 
> Verson: 3.4.3
> 

use 3.4.5
